### PR TITLE
Update copyright year

### PR DESCRIPTION
**Pull request by myabc**

### CODE REVIEW

**Comment by apotonick** [comment]
Someone told me you don't need to do that?

**Comment by myabc** [comment]
IANAL

**Comment by apotonick** [comment]
Excellent, thanks @sakuro !

**Comment by abinoam** [comment]
So... should @myabc update the PR to just
```Copyright (c) 2011 Nick Sutterer and the roar contributors``` ?

But... this is Representable, not roar. Shouldn't it be like bellow?

```Copyright (c) 2011 Nick Sutterer and the Representable contributors```

**Pull request closed without merging**
