### PR TITLE
Symbolizes keys when mapping an Object to a Hash.

### PR DESCRIPTION
**Pull request by vicentereig**
@apotonick  Hi there,

When serializing an object into a `Hash`, you may want to convert keys to `Symbol`s.

``` ruby
require 'representable/hash/symbolize_keys'

module SongRepresenter
  include Representable::Hash
  include Representable::Hash::SymbolizeKeys
  property :title
end

class Song < Struct.new(:title) ; end

Song.new('a title').extend(SongRepresenter).to_hash # => {title: 'a title'}
```

A couple of things open to discussion:
1. It introduces a dependency on `activesupport`. 
2. We could also use `Representable::Hash::AllowSymbols` to override `#to_hash` and symbolize the keys, but seems that it is only used when mapping a `Hash` to an `Object`.
3. Maybe just return a `Hash` with indifferent access?

### CODE REVIEW

**Comment by apotonick** [comment]
Cool idea, but we can't use ActiveSupport, sorry! This is a no-go in all my gems. :laughing: 

I like your idea of a new module. However, we also need to test nested representers when rendering. Are you willing to work on this? :heart:

**Comment by vicentereig** [comment]
> Cool idea, but we can't use ActiveSupport, sorry! This is a no-go in all my gems. :laughing:

Sounds good.

> I like your idea of a new module. However, we also need to test nested representers when rendering. Are you willing to work on this? :heart:

Sure thing, I'll keep you posted!

**Comment by apotonick** [comment]
Are you still interested in this PR? Would love to merge, without AS, though.

**Comment by seuros** [comment]
You can use `Representable::Hash::Conversion.symbolize_keys` now

**Pull request closed without merging**
